name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build EXE
      run: makensis tool.nsi

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: Toolkit-EXE
        path: Toolkit.exe
