name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install NSIS
      run: choco install nsis -y

    - name: Build EXE
      run: |
        & "C:\Program Files (x86)\NSIS\makensis.exe" tool.nsi

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Toolkit-EXE
        path: Toolkit.exe
